ALTER TABLE Divinita MODIFY COLUMN nome VARCHAR(50) NOT NULL;
ALTER TABLE Divinita MODIFY COLUMN razza VARCHAR(50) NOT NULL;
ALTER TABLE Divinita MODIFY COLUMN abilita VARCHAR(255) NOT NULL;
ALTER TABLE Divinita MODIFY COLUMN equipaggiamento VARCHAR(255) NOT NULL;